[connections.snowflake]
account = "MWB59269"
user = "JFLASHER43"
password = "Vivaldi$Train43"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
